services:
  - type: web
    name: niceguyapi
    runtime: docker
    repo: https://github.com/MrGhostGuy/niceguyapi
    branch: main
    rootDir: server
    plan: free
    envVars:
      - key: NICEGUYAPI_PORT
        value: "3000"
      - key: NICEGUYAPI_SECRET
        generateValue: true
      - key: NODE_ENV
        value: "production"
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
